# This Github workflow will run the Report step of the Ploigos workflow.
name: Minimal Workflow

on:
  workflow_call:
    inputs:
      verbose:
        required: false
        type: string
      image:
        required: true
        type: string
      imagePullPolicy:
        required: true
        type: string
      stepRunnerPackageName:
        required: true
        type: string
      venvPath:
        required: true
        type: string
      stepName:
        required: true
        type: string
      stepRunnerConfigDir:
        required: true
        type: string
jobs:
  continous-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: ci-generate-metadata
        run: psr --help
      - name: ci-package-application
        run: psr -s package-application
      - name: ci-create-container-image
        run: psr -s create-container-image
      - name: ci-push-container-image-to-repository
        run: psr -s push-container-image

