# This Github workflow will run the Report step of the Ploigos workflow.
name: Minimal Workflow

on:
  workflow_call:
    inputs:
      verbose:
        required: false
        type: string
      psrBranch:
        required: false
        type: string
        default: main
      stepRunnerConfigDir:
        required: true
        type: string
jobs:
  continous-integration:
    runs-on: ubuntu-latest
    steps:

      - name: setup-app-clone
        uses: actions/checkout@v3

      - name: setup-workflow-step-runner
        run: python -m pip install --upgrade git+https://github.com/ploigos/ploigos-step-runner.git@${{ inputs.psrBranch }}

      - name: ci-generate-metadata
        run: psr --help

      - name: ci-package-application
        run: psr --help

      - name: ci-create-container-image
        run: psr --help

      - name: ci-push-container-image-to-repository
        run: psr --help

